name: Code and build quality check
run-name: Check with android lint, detekt and unit tests
on: [ push ]
jobs:
  Linters-and-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-disabled: true

      - name: Lint
        shell: bash
        run: ./gradlew lint

      - name: Detekt
        shell: bash
        run: ./gradlew detekt reportMerge --continue

      - name: Unit tests
        shell: bash
        run: ./gradlew test